Web assert add timeout
alexislefebvre/Mink pull request #3
Opened 2017-02-01 20:24 UTC by alexislefebvre

2017-02-01 21:53 UTC, alexislefebvre commented on src/WebAssert.php
> +            $this->session->getPage()->waitFor($timeout, function () use ($cleanedUrl, &$actual) {
@lenybernard Do you think that we should keep the `waitFor()` for the address? I'm pretty sure that the address of a page is not supposed to change once a page if loaded (if Mink wait for redirections, I didn't check that).

2017-02-01 21:59 UTC, alexislefebvre commented on src/WebAssert.php
> +                return $actual !== $cleanedUrl;
@lenybernard I think that this condition can't work.

Let's say that the test expect the address to be different from `path/`:
- if the URL is `path/` during one second, then '/file', the test will work (after trying during one second)
- if the URL is `/file` during one second, then 'path/', the test will work, the condition will be evaluated to true during the first loop iteration, it won't wait several seconds, so the test will be marked as passed incorrectly

2017-02-01 22:56 UTC, lenybernard commented on src/WebAssert.php
> +            $this->session->getPage()->waitFor($timeout, function () use ($cleanedUrl, &$actual) {
Actually, the address could change with javascript so I guess it can be useful

2017-02-02 15:31 UTC, lenybernard requested changes
Please run php-cs-fixer before

2017-02-02 15:44 UTC, alexislefebvre commented on src/WebAssert.php
> +    const timeout = 5;
This must be documented in CHANGES.md and in README.md.

2017-02-02 15:45 UTC, lenybernard requested changes
please add also some kind of docs in `CHANGES.md` and add a use case in the `README.md` to show off what we can do now with this amazing timeout and how we can configure it

2017-02-02 15:45 UTC, lenybernard commented on src/WebAssert.php
> +    const timeout = 5;
constant should be uppercased please

2017-02-02 15:45 UTC, lenybernard commented on src/WebAssert.php
> +                // TODO Don't fail on first try if address are different.
remove comments please

2017-02-02 15:45 UTC, lenybernard commented on src/WebAssert.php
> +            $this->getMatchingElementRepresentation($selectorType, $selector, count($nodes) > 1),
why ?

2017-02-02 15:45 UTC, lenybernard commented on src/WebAssert.php
> +     * @param integer          $timeout      time to wait until fail
prefer float like waitFor method

2017-02-02 15:45 UTC, lenybernard commented on tests/WebAssertTest.php
> +/**
don't add these comments

2017-02-02 15:45 UTC, lenybernard commented on tests/WebAssertTest.php
> +    const timeoutLimit = 0.11;
explane here wtf is this value 🤓

2017-02-02 15:45 UTC, lenybernard commented on tests/WebAssertTest.php
> +    const timeoutLimit = 0.11;
uppercase

2017-03-16 20:47 UTC, closed without merging